# Generated by Django 4.2.11 on 2026-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='codice_postale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
