# Generated by Django 4.2.11 on 2026-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_zip_code_customuser_codice_postale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
