# Generated by Django 4.2.11 on 2026-07-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_balance',
        ),
    ]
