# Generated by Django 4.2.11 on 2026-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500', max_length=500),
        ),
    ]
