# Generated by Django 4.2.11 on 2026-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_citta_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('ricevuto', 'Ordine ricevuto'), ('spedizione', 'Spedizione'), ('transito', 'In transito'), ('consegna', 'In consegna'), ('consegnato', 'Consegnato')], default='ricevuto', max_length=20, verbose_name='Stato Spedizione'),
        ),
    ]
