# Generated by Django 4.2.11 on 2026-07-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_review_unique_per_user_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
