# Generated by Django 4.2.11 on 2026-07-07 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_orderitem_orderitem_price_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_price_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='product_price_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='product_stock_gte_0',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='orderitem_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='product_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='product_stock_gte_zero'),
        ),
    ]
