# Generated by Django 4.2.11 on 2026-07-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_coupon_order_discount_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
    ]
