# Generated by Django 4.2.11 on 2026-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_delete_coupon_remove_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carta di Credito'), ('paypal', 'PayPal'), ('transfer', 'Bonifico Bancario')], default='card', max_length=50, verbose_name='Metodo di Pagamento'),
        ),
    ]
