# Generated by Django 4.2.11 on 2026-07-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_assign_discountcode_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='active',
        ),
    ]
