# Generated by Django 4.2.11 on 2026-07-09 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fisso (€)'), ('percentage', 'Percentuale (%)')], default='fixed', max_length=15, verbose_name='Tipo di Sconto'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valore Sconto'),
        ),
    ]
